fix 'ValueError: invalid literal' caused by empty strings in lispAction
```
scriptName = '840203'
```
```
# alpha 131  0 0.5
```
https://github.com/Glasislundr/PotK-Threnody/blob/dae1fc7b8a629c58f646bea3e6c53aadc60d3f37/lib/story_viewer/ParsedScriptFile.py#L78
```
Traceback (most recent call last):
  File "C:\Users\laqieer\source\repos\laqieer\PotK-Threnody\05_read_story.py", line 51, in <module>
    theScript = ParsedScriptFile(scriptName)
  File "C:\Users\laqieer\source\repos\laqieer\PotK-Threnody\lib\story_viewer\ParsedScriptFile.py", line 19, in __init__
    self.parse(line)
  File "C:\Users\laqieer\source\repos\laqieer\PotK-Threnody\lib\story_viewer\ParsedScriptFile.py", line 69, in parse
    self.actions.extend([ScriptFileActions.SetCharacterPos(int(lispAction[1]), int(lispAction[2]))])
ValueError: invalid literal for int() with base 10: ''
```